### ISSUE TITLE
Add event_timestamp to event

### ISSUE THREAD

**Issue by drdee** [Shopify/presto-logging-plugin#8]
For Camus to be able to drop the event in the right partition, it needs an `event_timestamp` field.

@johnjmartin

**Comment by johnjmartin** [comment]
@drdee Is [Queryevent Endtime](https://github.com/Shopify/presto-logging-plugin/blob/master/src/main/java/com/shopify/presto/eventlisteners/QueryLogEventListener.java#L74) appropriate?

**Comment by drdee** [comment]
I would just use the timestamp of when you emit the event.

**Comment by johnjmartin** [comment]
What is the format Camus expects for `event_timestamp`?

**Comment by drdee** [comment]
https://github.com/Shopify/cookbooks/blob/master/roles/app/hadoop/camus.rb#L57
